apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: els-cidr-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Elsgit1/els-cidr-app.git
    targetRevision: main
    path: k8s-deployment
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true